##
##  Makefile -- Build procedure for sample replace_handler Apache module
##  Autogenerated via ``apxs -n replace_handler -g''.
##

TARGET=mod_replace_handler.c

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional user defines, includes and libraries
DEF=
INC=
LIB=
WC=-Wc,-std=c99

#   the default target
all: mod_replace_handler.la

mod_replace_handler.la: $(TARGET)
	$(APXS) -c $(DEF) $(INC) $(LIB) $(WC) $(TARGET)

#   install the shared object file into Apache
install: all
	$(APXS) -i -a -n 'replace_handler' mod_replace_handler.la

#   cleanup
clean:
	-rm -rf .libs mod_replace_handler.o mod_replace_handler.lo mod_replace_handler.slo mod_replace_handler.la

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

