##
##  Makefile -- Build procedure for sample swap_handler Apache module
##  Autogenerated via ``apxs -n swap_handler -g''.
##

TARGET=mod_swap_handler.c

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   the default target
all: mod_swap_handler.la

mod_swap_handler.la: $(TARGET)
	$(APXS) -c $(TARGET)

#   install the shared object file into Apache 
install: all
	$(APXS) -i -a -n 'swap_handler' mod_swap_handler.la

#   cleanup
clean:
	-rm -rf .libs mod_swap_handler.o mod_swap_handler.lo mod_swap_handler.slo mod_swap_handler.la 

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

